[package]
name = "apib"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.11", features = ["native-tls"] }
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros"]}
